.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139,
.\" USA.
.\"
.TH mondorestore 8 "DDD" "Mondo Rescue VVV-rRRR"

.SH NAME
mondorestore \- a restore / disaster\-recovery tool.

.SH SYNOPSIS
.B mondorestore
: restore your PC

.SH DESCRIPTION
.PP
.I mondorestore
restores data previously backed up with 
.I mondoarchive
\&. mondoarchive does not take any command line parameters.
.
Note that mondorestore will usually automatically be called when booting a 
MondoRescue medium. The only exception is booting a MondoRescue medium in
.B Expert
mode in which case mondorestore can be evoked from the command line.

.SH DIAGNOSTICS
mondorestore generates an Extremely important file:
.BI /var/log/mondo-archive.log. 
When seeking technical support, attach this file to your email. 

.SH FILES
.IR /var/log/mondo-archive.log
This log contains important information required to analyse mondorestore problem
reports. Mondo support highly recommends sending this file with support
questions.

.SH NOTES
A link to Mondo's HTML-based manual (by Bruno Cornec, Mikael Hultgren, Cafeole, Randy Delphs,
Stan Benoit, and Hugo Rabson) may be found at
.I http://www.mondorescue.org/docs.shtml
- or in 
.I /usr/share/doc/mondo-x.xx
on your hard drive.

.SH BUGS
It is recommend that your system has more than 64 MB ram. SCSI device order
change with nuke can have unexpected results. It is recommended you use expert
mode with drastic hardware reconfigurations. 

.SH "SEE ALSO"
afio(1), bzip2(1), find(1), mindi(8), mondoarchive(8).
.SH AUTHORS
Bruno Cornec (lead-development) 
.I "bruno_at_mondorescue.org"
.br
Andree Leidenfrost (co-developper) 
.I "aleidenf_at_bigpond.net.au"
.br
.SH ORIGINAL AUTHORS
Hugo Rabson (original author)
.I "hugo.rabson_at_mondorescue.org"
.br
Jesse Keating (packaging)
.I "hosting_at_j2solutions.net"
.br
Stan Benoit (testing)
.I "troff_at_nakedsoul.org"
.br
Mikael Hultgren (docs)
.I "mikael_hultgren_at_gmx.net"
.br
See mailing list at http://www.mondorescue.org for technical support.
.
