#!/bin/bash
#
# Creates common environment 
#
# $Id$
#

# Adapt to your needs
export BASE=${HOME}/mondo
export TOPDIR=${BASE}/build
mkdir -p ${TOPDIR}
export TMPDIR=
export TMP=`mktemp -d -p /tmp`

umask 022
