#!/bin/bash
#
# Creates Gentoo environment from SVN repository
#
# $Id$
#

dname=`dirname $0`
prem=`echo $dname |cut -c1`
if [ ${prem} == "/" ]; then
        export TOOLHOME=$dname
else
	export TOOLHOME=${PWD}/$dname
fi

. $TOOLHOME/common-env

#export ARCH=`rpm --showrc | egrep "^build arch" | awk '{print $4}'`

# Should not be modified below
export pkg=""
export opt=""
export ARCH=""

export TOPDIR=${BASE}/ebuild
mkdir -p ${TOPDIR}

export dfam="gentoo"
export ddir="gentoo"
export dver=`awk '{print $4}' /etc/gentoo-release`
export suf=".`echo $dver | sed 's/\.//'`"

if [ _"$suf" = _"" ]; then
	export suf=".${ddir}${dver}"
fi
