#!/bin/bash
#
# Creates debs packages from SVN repository for local tests
#
# $Id$
#

umask 022
dname=`dirname $0`
prem=`echo $dname |cut -c1`
if [ ${prem} == "/" ]; then
	export TOOLHOME=$dname
else
	export TOOLHOME=${PWD}/$dname
fi

. $TOOLHOME/deb-env

if [ "$1" = "" ]; then
	c="mindi mondo"
else
	c=$1
fi

$TOOLHOME/mkcommon "$c"

if [ "`echo $c | grep mindi-kernel`" != "" ]; then
	cd ${BASE}/svn
	mkdir -p ${TOPDIR}/SOURCES 
	$TOOLHOME/mkspec ${MINDI_VER} mindi-kernel-${MINDI_VER}/mindi-kernel.spec > ${TOPDIR}/SPECS/mindi-kernel.spec
	chmod 644 ${TOPDIR}/SPECS/mindi-kernel.spec
	pkg1="${TOPDIR}/RPMS/${ARCH}/mindi-kernel-${MINDI_VER}-${REVISION}${suf}.${ARCH}.rpm"
	pkg="$pkg $pkg1"
	rm -f $pkg1
fi
if [ "`echo $c | grep -v kernel | grep mindi`" != "" ]; then
	cd ${BASE}/svn
	$TOOLHOME/mkspec ${MINDI_VER} mindi-${MINDI_VER}/distributions/rpm/mindi.spec > ${TOPDIR}/SPECS/mindi.spec
	cat mindi-${MINDI_VER}/distributions/$dfam/changelog >> ${TOPDIR}/SPECS/mindi.spec
	chmod 644 ${TOPDIR}/SPECS/mindi.spec
	rm -rf mindi-${MINDI_VER}/distributions
	mkdir -p ${TOPDIR}/SOURCES 

	pkg1="${TOPDIR}/RPMS/${ARCH}/mindi-${MINDI_VER}-${REVISION}${suf}.${ARCH}.rpm"
	pkg="$pkg $pkg1"
	rm -f $pkg1
fi
if [ "`echo $c | grep  mondo`" != "" ]; then
	cd ${BASE}/svn
	$TOOLHOME/mkspec ${MONDO_VER} mondo-${MONDO_VER}/distributions/rpm/mondo.spec > ${TOPDIR}/SPECS/mondo.spec
	cat mondo-${MONDO_VER}/distributions/$dfam/changelog >> ${TOPDIR}/SPECS/mondo.spec
	chmod 644 ${TOPDIR}/SPECS/mondo.spec
	rm -rf mondo-${MONDO_VER}/distributions

	pkg1="${TOPDIR}/RPMS/${ARCH}/mondo-${MONDO_VER}-${REVISION}${suf}.${ARCH}.rpm"
	pkg="$pkg $pkg1"
	rm -f $pkg1
fi

cd ${TOPDIR}/SPECS
status=0
for p in "$c"; do
	echo "Generating $p deb"
	log=/tmp/$p-deb.log
	#rpmbuild -ba $p.spec 2> $log 1> $log
	if [ $? != 0 ]; then 
		cat $log
		status=-1
	fi
fi
if [ $status = 0 ]; then
	echo "Installing deb as root ($pkg)"
	su - -c "$opt rpm -Uvh --force $pkg"
fi
