#!/bin/bash
#
# Deliver RPMs packages and tgz files to BerliOS

. ./rpm-env

tgz=""
srpms=""
rpms=""
ct=`date "+%Y%m%d"`

if [ "$1" = "" ]; then
	c="mindi mondo"
else
	c=$1
fi
if [ "`echo $c | grep mindi`" != "" ]; then
	cp -a ${TOPDIR}/SOURCES/mindi-${MINDI_VER}.tgz ${TOPDIR}/SOURCES/mindi-${MINDI_VER}-${ct}.tgz
	tgz="$tgz ${TOPDIR}/SOURCES/mindi-${MINDI_VER}-${ct}.tgz"
	rpms="$rpms ${TOPDIR}/RPMS/${ARCH}/mindi-${MINDI_VER}-1.${ARCH}.rpm"
	srpms="$srpms ${TOPDIR}/SRPMS/mindi-${MINDI_VER}-1.src.rpm"
fi
if [ "`echo $c | grep  mondo`" != "" ]; then
	cp -a ${TOPDIR}/SOURCES/mondo-${MONDO_VER}.tgz ${TOPDIR}/SOURCES/mondo-${MONDO_VER}-${ct}.tgz
	tgz="$tgz ${TOPDIR}/SOURCES/mondo-${MONDO_VER}-${ct}.tgz"
	rpms="$rpms ${TOPDIR}/RPMS/${ARCH}/mondo-${MONDO_VER}-1.${ARCH}.rpm"
	srpms="$srpms ${TOPDIR}/SRPMS/mondo-${MONDO_VER}-1.src.rpm"
fi
scp -p ${tgz} ${SVNAUTH}:${DSTDIR}/TGZ
scp -p ${rpms} ${SVNAUTH}:${DSTDIR}/RPMS
scp -p ${srpms} ${SVNAUTH}:${DSTDIR}/SRPMS
ncftpput ${FTPURL} ${tgz}
