#!/bin/bash
#
# $Id$
#
# Call virtual machine with qemu
#

if [ _"$1" == _"" ]; then
	echo "Syntax: qemu vm"
	exit -1
else
	m=$1
fi

ipvm=10.0.2.15

if [ _"$sp" = _"" ]; then
	sp=2223
fi

qemu -m 256 $QEMUOPT -redir tcp:${sp}:${ipvm}:22 /users/qemu/$m.qemu
