#!/bin/bash
#
# $Id$
#
# test script for library functions
#
	gcc -O2 -I../common test-conf.c ../common/libmondo-conf.c ../common/libmondo-msg.c -o test-conf
for f in "test-conf"; do
	chmod 755 $f
	./$f > /tmp/$f.res
	diff -q $f.res /tmp/$f.res
	if [ $? -ne 0 ]; then
		echo "$f test KO !!"
	fi
done
