#!/bin/bash
#
# Creates RPMs environment from SVN repository
#
# $Id$
#

# Adapt to your needs
export BASE=${HOME}/mondo
export SVNAUTH=bcornec@shell.berlios.de
export DSTDIR=/home/groups/ftp/pub/mondorescue
export FTPURL="ftp.berlios.de /incoming"

# Should not be modified below
export VER=branches/2.04_berlios
export pkg=""
export opt=""
export ARCH=`rpm --showrc | egrep "^build arch" | awk '{print $4}'`

mkdir -p ${BASE}/RPMS
export TMP=${BASE}/tmp
mkdir -p ${TMP}
if [ -f ${HOME}/.rpmmacros ]; then
	export TOPDIR=`egrep '^%_topdir' ${HOME}/.rpmmacros | awk '{print $2}'`
else
	export TOPDIR=${BASE}/RPMS
fi
cd ${TOPDIR}
mkdir -p RPMS SRPMS SPECS SOURCES BUILD

export MINDI_VER=`cat ${BASE}/svn/${VER}/mindi/mindi.spec | egrep '^%define version' | awk '{print $3}' | sed "s/[ 	]*//"`
export MONDO_VER=`cat ${BASE}/svn/${VER}/mondo/mondo.spec | egrep '^%define version' | awk '{print $3}' | sed "s/[ 	]*//"`

if [ -e /etc/mandriva-release ]; then
		export suf=mdk
elif [ -e /etc/mandrake-release ]; then
		export suf=mdk
else
		export suf=""
fi
