.\" Copyright (c) 2005 Andree Leidenfrost
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139,
.\" USA.
.\"
.TH MINDI 8 "DDD" "Mondo Rescue VVV-rRRR"
.SH NAME
mindi \- a tool for creating boot/root disks
.SH SYNOPSIS
.B mindi
.br
.BR "mindi -v"| " --version"| " -V"| " -version"
.br
.BI "mindi --findkernel"
.br
.BI "mindi --makemountlist "file
.br
.BI "mindi [--max-compressed-size "max "] --custom " parameters
.SH DESCRIPTION
.PP
.B mindi
creates a set of boot/root floppy disk images and/or a bootable ISO image using
files from the system it runs on.
.B mindi
will try hard to reproduce the environment of its host system including loaded
modules to ensure that the system can be booted properly from the created
rescue media.
.B mindi
is used by
.B monodarchive(8)
to produce the required boot/root floppy or CD images but can also be used
stand-alone.

For stand-alone usage,
.B mindi
is called without any parameters or switches. It will then interactively ask
the user for all information required to create a set of boot/root media.
.LP
The probably more frequent way of calling
.B mindi
is non-interactively from
.B mondoarchive(8)
using the
.B --custom
switch. All required information is then provided via command line parameters.
The sequence of these parameters is listed below.
.SH OPTIONS
.TP
.BR "-v"| " --version"| " -V"| " -version"
Prints the version of mindi.
.TP
.B --findkernel
Finds the image of the running kernel in the file system.
.TP
.BI "--makemountlist "file
.RI "Creates a mount list and writes it to file "file ".
.TP
.BI "--max-compressed-size "max
Maximum size for disk image in KB.
.TP
.BI "--custom " parameters
Provide all required parameters to
.B mindi
for non-interactive calling. This usually means a call from
.BR "mondoarchive(8)".
The following parameters are used:
.br
01) directory to use for temporary files
.br
02) directory to put disk images in
.br
03) path to kernel image
.br
04) tape device
.br
05) tape size [MB]
.br
06) total number of files in file list
.br
07) use LZO [yes|no]
.br
08) CD recovery media [yes|no]
.br
09) devices to include
.br
10) conservative LiLo settings [yes|no]
.br
11) number of last file list
.br
12) estimated total number of slices
.br
13) devices to exclude
.br
14) compare mode [yes|no]
.br
15) use lilo [yes|no]
.br
16) use star (rather than tar) [yes|no]
.br
17) internal tape block size [bytes]
.br
18) number of diffenrential backup
.br
19) make non-bootable [yes|no]
.br
(Blank parameters must be specified as "" on the command line.)
.SH DIAGNOSTICS
.B mindi
writes some output to the console and extensive information to log file
.IR /var/log/mindi.log ".
When seeking technical support for
.BR "mindi",
please attach this file to your email.
.SH FILES
.TP
.I /var/log/mindi.log
Log file of mindi run. Contains important information to analyze mindi problem
reports.
.TP
.I /etc/mindi/deplist.txt 
List of files to be included on boot/root disks.
.TP
.I /root/images/mindi/N.tar.gz
Number N of multiple tar balls together containing root file system for rescue
media.
.TP
.I /root/images/mindi/all.tar.gz
Single tar ball of root file system for rescue media.
.TP
.I /root/images/mindi/initrd.img
initrd image for bootable ISO image.
.TP
.I /root/images/mindi/mindi-boot.F.img
.B mindi
boot floppy of size F [KB].
.TP
.I /root/images/mindi/mindi-root.F.img
.B mindi
root floppy of size F [KB].
.TP
.I /root/images/mindi/mindi-data.N.img
.B mindi
data floppy number N for boot/root floppies.
.TP
.I /root/images/mindi/mindi.iso
.B mindi
bootable ISO image.
.SH "SEE ALSO"
mondoarchive(8), mondorestore(8).
.TP
See mailing list at http://www.mondorescue.org for technical support.
.SH BUGS
The target location for the image files created by
.B mindi
is hard-coded to
.IR "/root/images/mindi".
As a workaround, it is suggested to make
.I /root/images
a symbolic link to the desired location for the image files.
.SH AUTHORS
Bruno Cornec (lead-development) 
.I "bcornec_at_users.berlios.de"
.br
Andree Leidenfrost (co-developper) 
.I "aleidenf_at_bigpond.net.au"
.br
.SH ORIGINAL AUTHORS
Hugo Rabson (original author)
.I "hugo.rabson_at_mondorescue.org"
.br
Jesse Keating (packaging)
.I "hosting_at_j2solutions.net"
.br
Stan Benoit (testing)
.I "troff_at_nakedsoul.org"
.br
Mikael Hultgren (docs)
.I "mikael_hultgren_at_gmx.net"
.br
.
