.TH mondorestore 8 "February 2006" Linux MondoRescue

.SH NAME
mondorestore \- a restore / disaster\-recovery tool.

.SH SYNOPSIS
.B mondorestore
: restore your PC

.SH DESCRIPTION
.PP
.I mondorestore
restores data previously backed up with 
.I mondoarchive
\&. mondoarchive does not take any command line parameters.
.
Note that mondorestore will usually automatically be called when booting a 
MondoRescue medium. The only exception is booting a MondoRescue medium in
.B Expert
mode in which case mondorestore can be evoked from the command line.

.SH DIAGNOSTICS
mondorestore generates an Extremely important file:
.BI /var/log/mondo-archive.log. 
When seeking technical support, attach this file to your email. 

.SH FILES
.IR /var/log/mondo-archive.log
This log contains important information required to analyse mondorestore problem
reports. Mondo support highly recommends sending this file with support
questions.

.SH NOTES
A link to Mondo's HTML-based manual (by Bruno Cornec, Mikael Hultgren, Cafeole, Randy Delphs,
Stan Benoit, and Hugo Rabson) may be found at
.I http://www.mondorescue.org/docs.shtml
- or in 
.I /usr/share/doc/mondo-x.xx
on your hard drive.

.SH BUGS
It is recommend that your system has more than 64 MB ram. SCSI device order
change with nuke can have unexpected results. It is recommended you use expert
mode with drastic hardware reconfigurations. 

.SH "SEE ALSO"
afio(1), bzip2(1), find(1), mindi(8), mondoarchive(8).
.SH AUTHORS
Bruno Cornec (lead-development) 
.I "bcornec_at_users.berlios.de"
.br
Andree Leidenfrost (co-developper) 
.I "aleidenf_at_bigpond.net.au"
.br
.SH ORIGINAL AUTHORS
Hugo Rabson (original author)
.I "hugo.rabson_at_mondorescue.org"
.br
Jesse Keating (packaging)
.I "hosting_at_j2solutions.net"
.br
Stan Benoit (testing)
.I "troff_at_nakedsoul.org"
.br
Mikael Hultgren (docs)
.I "mikael_hultgren_at_gmx.net"
.br
See mailing list at http://www.mondorescue.org for technical support.
.
