#!/bin/bash
#
# Deliver RPMs packages and tgz files to BerliOS
#
# $Id$
#

# BerliOS FTP/SSH setup
BERLIOSAC=bcornec@shell.berlios.de
DSTDIR=/home/groups/ftp/pub/mondorescue
FTPSERV="ftp.berlios.de"
FTPDIR="/incoming"

dname=`dirname $0`
prem=`echo $dname |cut -c1`
if [ ${prem} == "/" ]; then
        export TOOLHOME=$dname
else
	export TOOLHOME=${PWD}/$dname
fi

. $TOOLHOME/rpm-env

tgz=""
srpms=""
rpms=""
rev=`$TOOLHOME/mksvnversion`

if [ "$1" = "" ]; then
	c="mindi mondo"
else
	c=$1
fi
if [ "`echo $c | grep mindi`" != "" ]; then
	cp -a ${TOPDIR}/SOURCES/mindi-${MINDI_VER}.tgz ${TOPDIR}/SOURCES/mindi-${MINDI_VER}-r${rev}.tgz
	cp -a ${TOPDIR}/SOURCES/mindi-${MINDI_VER}.tar.bz2 ${TOPDIR}/SOURCES/mindi-${MINDI_VER}-r${rev}.tar.bz2
	tgz="$tgz ${TOPDIR}/SOURCES/mindi-${MINDI_VER}-r${rev}.tgz ${TOPDIR}/SOURCES/mindi-${MINDI_VER}-r${rev}.tar.bz2"
	rpms="$rpms ${TOPDIR}/RPMS/${ARCH}/mindi-${MINDI_VER}-${rev}.${suf}.${ARCH}.rpm"
	srpms="$srpms ${TOPDIR}/SRPMS/mindi-${MINDI_VER}-${rev}.${suf}.src.rpm"
fi
if [ "`echo $c | grep  mondo`" != "" ]; then
	cp -a ${TOPDIR}/SOURCES/mondo-${MONDO_VER}.tgz ${TOPDIR}/SOURCES/mondo-${MONDO_VER}-r${rev}.tgz
	cp -a ${TOPDIR}/SOURCES/mondo-${MONDO_VER}.tar.bz2 ${TOPDIR}/SOURCES/mondo-${MONDO_VER}-r${rev}.tar.bz2
	tgz="$tgz ${TOPDIR}/SOURCES/mondo-${MONDO_VER}-r${rev}.tgz ${TOPDIR}/SOURCES/mondo-${MONDO_VER}-r${rev}.tar.bz2"
	rpms="$rpms ${TOPDIR}/RPMS/${ARCH}/mondo-${MONDO_VER}-${rev}.${suf}.${ARCH}.rpm"
	srpms="$srpms ${TOPDIR}/SRPMS/mondo-${MONDO_VER}-${rev}.${suf}.src.rpm"
fi
echo "Sources delivery to ${BERLIOSAC}:${DSTDIR}/src"
scp ${tgz} ${BERLIOSAC}:${DSTDIR}/src
ssh ${BERLIOSAC} "mkdir -p ${DSTDIR}/${ddir}/${dver}"
echo "Packages delivery to ${BERLIOSAC}:${DSTDIR}/${ddir}/${dver}"
scp ${rpms} ${BERLIOSAC}:${DSTDIR}/${ddir}/${dver}
scp ${srpms} ${BERLIOSAC}:${DSTDIR}/${ddir}/${dver}
echo "Sources delivery to ${FTPSERV} ${FTPDIR}"
if [ "`which ncftpput`" != "" ]; then
	ncftpput ${FTPSERV} ${FTPDIR} ${tgz}
elif [ "`which lftp`" != "" ]; then
	lftp -e "cd ${FTPDIR} ; put ${tgz} ; quit" ${FTPSERV}
fi
