#!/bin/bash
#
# Creates common environment from SVN repository
#
# $Id$
#

# Adapt to your needs
export BASE=${HOME}/mondo
export TOPDIR=${BASE}/RPMS
mkdir -p ${TOPDIR}

# Should not be modified below
dname=`dirname $0`
export SVNBRANCH="branches/`cat ${TOOLHOME}/../mondo/VERSION`"
export TMP=${BASE}/tmp
mkdir -p ${TMP}

export MINDI_VER=`cat ${BASE}/svn/${SVNBRANCH}/mindi/VERSION`
export MONDO_VER=`cat ${BASE}/svn/${SVNBRANCH}/mondo/VERSION`

# To be safe for SVN commands
cd $TOOLHOME/..
export REVISION=`svnversion .`
