#!/bin/bash
#
# Deliver packages and tgz files to ftp.mondorescue.org
#
# $Id$
#

# BerliOS FTP/SSH setup
ACCOUNT=bruno@ftp.mondorescue.org
DSTDIR=/mondo/ftp
FTPSERV="ftp.berlios.de"
FTPDIR="/incoming"

dname=`dirname $0`
prem=`echo $dname |cut -c1`
if [ ${prem} == "/" ]; then
        export TOOLHOME=$dname
else
	export TOOLHOME=${PWD}/$dname
fi

. $TOOLHOME/common-env
. $TOOLHOME/distro-env

# We need to get $VER and $TAG
if [ "$1" = "" ]; then
	LAST=`cat ${TOPDIR}/LAST`
else
	LAST=$1
	shift
fi
VER=`echo $LAST | cut -d- -f1`
TAG=`echo $LAST | cut -d- -f2`
echo "Working on ${VER}-$TAG"
	
if [ "$1" = "" ]; then
	c="mondo-doc mindi mondo"
else
	if [ "$1" = "all" ]; then
		c="mindi-kernel mondo-doc mindi mondo"
	else
		c=$1
	fi
fi

export pkg=""
echo "Working under $TOPBUILDDIR"
cd $TOPBUILDDIR

for p in $c; do

tgz=""
srpms=""
rpms=""

if [ "`echo $c | grep mindi`" != "" ]; then
	cp -a ${TOPBUILDDIR}/SOURCES/mindi-${MINDI_VER}.tgz ${TOPBUILDDIR}/SOURCES/mindi-${MINDI_VER}-r${rev}.tgz
	cp -a ${TOPBUILDDIR}/SOURCES/mindi-${MINDI_VER}.tar.bz2 ${TOPBUILDDIR}/SOURCES/mindi-${MINDI_VER}-r${rev}.tar.bz2
	tgz="$tgz ${TOPBUILDDIR}/SOURCES/mindi-${MINDI_VER}-r${rev}.tgz ${TOPBUILDDIR}/SOURCES/mindi-${MINDI_VER}-r${rev}.tar.bz2"
	rpms="$rpms ${TOPBUILDDIR}/RPMS/${ARCH}/mindi-${MINDI_VER}-${rev}${suf}.${ARCH}.rpm"
	srpms="$srpms ${TOPBUILDDIR}/SRPMS/mindi-${MINDI_VER}-${rev}${suf}.src.rpm"
fi
if [ "`echo $c | grep mondo-doc`" != "" ]; then
	cp -a ${TOPBUILDDIR}/SOURCES/mondo-doc-${MONDO_VER}.tgz ${TOPBUILDDIR}/SOURCES/mondo-doc-${MONDO_VER}-r${rev}.tgz
	cp -a ${TOPBUILDDIR}/SOURCES/mondo-doc-${MONDO_VER}.tar.bz2 ${TOPBUILDDIR}/SOURCES/mondo-doc-${MONDO_VER}-r${rev}.tar.bz2
	tgz="$tgz ${TOPBUILDDIR}/SOURCES/mondo-doc-${MONDO_VER}-r${rev}.tgz ${TOPBUILDDIR}/SOURCES/mondo-doc-${MONDO_VER}-r${rev}.tar.bz2"
	rpms="$rpms ${TOPBUILDDIR}/RPMS/${ARCH}/mondo-doc-${MONDO_VER}-${rev}${suf}.${ARCH}.rpm"
	srpms="$srpms ${TOPBUILDDIR}/SRPMS/mondo-${MONDO_VER}-${rev}${suf}.src.rpm"
fi
if [ "`echo $c | grep -v doc | grep mondo`" != "" ]; then
	cp -a ${TOPBUILDDIR}/SOURCES/mondo-${MONDO_VER}.tgz ${TOPBUILDDIR}/SOURCES/mondo-${MONDO_VER}-r${rev}.tgz
	cp -a ${TOPBUILDDIR}/SOURCES/mondo-${MONDO_VER}.tar.bz2 ${TOPBUILDDIR}/SOURCES/mondo-${MONDO_VER}-r${rev}.tar.bz2
	tgz="$tgz ${TOPBUILDDIR}/SOURCES/mondo-${MONDO_VER}-r${rev}.tgz ${TOPBUILDDIR}/SOURCES/mondo-${MONDO_VER}-r${rev}.tar.bz2"
	rpms="$rpms ${TOPBUILDDIR}/RPMS/${ARCH}/mondo-${MONDO_VER}-${rev}${suf}.${ARCH}.rpm"
	srpms="$srpms ${TOPBUILDDIR}/SRPMS/mondo-${MONDO_VER}-${rev}${suf}.src.rpm"
fi
echo "Sources delivery to ${ACCOUNT}:${DSTDIR}/src"
scp ${tgz} ${ACCOUNT}:${DSTDIR}/src

echo "Packages delivery to ${ACCOUNT}:${DSTDIR}/${ddir}/${dver}"
ssh ${ACCOUNT} "mkdir -p ${DSTDIR}/${ddir}/${dver}"
scp ${rpms} ${srpms} ${ACCOUNT}:${DSTDIR}/${ddir}/${dver}

echo "Sources delivery to ${FTPSERV} ${FTPDIR}"
if [ "`which ncftpput`" != "" ]; then
	ncftpput ${FTPSERV} ${FTPDIR} ${tgz}
elif [ "`which lftp`" != "" ]; then
	lftp -e "cd ${FTPDIR} ; put ${tgz} ; quit" ${FTPSERV}
fi
