#!/bin/bash
#
# Creates Gentoo packages from SVN repository
#
# $Id$
#

umask 022
dname=`dirname $0`
prem=`echo $dname |cut -c1`
if [ ${prem} == "/" ]; then
	export TOOLHOME=$dname
else
	export TOOLHOME=${PWD}/$dname
fi

. $TOOLHOME/gentoo-env

if [ "$1" = "" ]; then
	c="mindi mondo"
else
	c=$1
fi

$TOOLHOME/mkcommon "$c"

if [ "`echo $c | grep mindi-kernel`" != "" ]; then
	cd ${BASE}/svn
	mkdir -p ${TOPDIR}/SOURCES 
	$TOOLHOME/mkebuild ${MINDI_VER} mindi-kernel-${MINDI_VER}/mindi-kernel.ebuild > ${TOPDIR}/ebuild/mindi-kernel.ebuild
	chmod 644 ${TOPDIR}/ebuild/mindi-kernel.ebuild
	pkg1="${TOPDIR}/ebuild/mindi-kernel-${MINDI_VER}-${REVISION}${suf}.${ARCH}.rpm"
	pkg="$pkg $pkg1"
	rm -f $pkg1
fi
if [ "`echo $c | grep -v kernel | grep mindi`" != "" ]; then
	cd ${BASE}/svn
	$TOOLHOME/mkebuild ${MINDI_VER} mindi-${MINDI_VER}/distributions/rpm/mindi.ebuild > ${TOPDIR}/ebuild/mindi.ebuild
	cat mindi-${MINDI_VER}/distributions/$dfam/changelog >> ${TOPDIR}/ebuild/mindi.ebuild
	chmod 644 ${TOPDIR}/ebuild/mindi.ebuild
	rm -rf mindi-${MINDI_VER}/distributions
	mkdir -p ${TOPDIR}/SOURCES 

	pkg1="${TOPDIR}/ebuild/mindi-${MINDI_VER}-${REVISION}${suf}.${ARCH}.rpm"
	pkg="$pkg $pkg1"
	rm -f $pkg1
	# ATTENTION: This could be dangerous for your setup
	opt="rm -rf /usr/lib/mindi ;"
fi
if [ "`echo $c | grep  mondo`" != "" ]; then
	cd ${BASE}/svn
	$TOOLHOME/mkebuild ${MONDO_VER} mondo-${MONDO_VER}/distributions/rpm/mondo.ebuild > ${TOPDIR}/ebuild/mondo.ebuild
	cat mondo-${MONDO_VER}/distributions/$dfam/changelog >> ${TOPDIR}/ebuild/mondo.ebuild
	chmod 644 ${TOPDIR}/ebuild/mondo.ebuild
	rm -rf mondo-${MONDO_VER}/distributions

	pkg1="${TOPDIR}/ebuild/mondo-${MONDO_VER}-${REVISION}${suf}.${ARCH}.rpm"
	pkg="$pkg $pkg1"
	rm -f $pkg1
fi

cd ${TOPDIR}/ebuild
status=0
if [ "`echo $c | grep kernel`" != "" ]; then
	echo "Generating mindi-kernel ebuild"
	log=/tmp/mindi-kernel-ebuild.log
	rpmbuild -ba mindi-kernel.ebuild 2> $log 1> $log
	if [ $? != 0 ]; then 
		cat $log
		status=-1
	fi
fi
if [ "`echo $c | grep -v kernel | grep mindi`" != "" ]; then
	echo "Generating mindi ebuild"
	log=/tmp/mindi-ebuild.log
	rpmbuild -ba mindi.ebuild 2> $log 1> $log
	if [ $? != 0 ]; then
		cat $log
		status=-1
	fi
fi
if [ "`echo $c | grep mondo`" != "" ]; then
	echo "Generating mondo ebuild"
	log=/tmp/mondo-ebuild.log
	rpmbuild -ba mondo.ebuild 2> $log 1> $log
	if [ $? != 0 ]; then 
		cat $log
		status=-1
	fi
fi
if [ $status = 0 ]; then
	echo "Installing ebuild as root ($pkg)"
	su - -c "$opt rpm -Uvh --force $pkg"
fi
