#!/bin/bash
#
# Creates RPMs packages from SVN repository for local tests
#
# $Id$
#

umask 022
dname=`dirname $0`
prem=`echo $dname |cut -c1`
if [ ${prem} == "/" ]; then
	export TOOLHOME=$dname
else
	export TOOLHOME=${PWD}/$dname
fi

. $TOOLHOME/rpm-env

if [ "$1" = "" ]; then
	c="mondo-doc mindi mondo"
else
	if [ "$1" = "all" ]; then
		c="mindi-kernel mondo-doc mindi mondo"
	else
		c=$1
	fi
fi

$TOOLHOME/mkcommon "$c"

if [ "`echo $c | grep mindi-kernel`" != "" ]; then
	cd ${BASE}/svn
	mkdir -p ${TOPDIR}/SOURCES 
	$TOOLHOME/mkspec ${MINDI_VER} mindi-kernel-${MINDI_VER}/mindi-kernel.spec > ${TOPDIR}/SPECS/mindi-kernel.spec
	chmod 644 ${TOPDIR}/SPECS/mindi-kernel.spec
	pkg1="${TOPDIR}/RPMS/${ARCH}/mindi-kernel-${MINDI_VER}-${REVISION}${suf}.${ARCH}.rpm"
	pkg="$pkg $pkg1"
	rm -f $pkg1
fi
if [ "`echo $c | grep -v kernel | grep mindi`" != "" ]; then
	cd ${BASE}/svn
	$TOOLHOME/mkspec ${MINDI_VER} mindi-${MINDI_VER}/distributions/rpm/mindi.spec > ${TOPDIR}/SPECS/mindi.spec
	cat mindi-${MINDI_VER}/distributions/$dfam/changelog >> ${TOPDIR}/SPECS/mindi.spec
	chmod 644 ${TOPDIR}/SPECS/mindi.spec
	rm -rf mindi-${MINDI_VER}/distributions
	mkdir -p ${TOPDIR}/SOURCES 

	pkg1="${TOPDIR}/RPMS/${ARCH}/mindi-${MINDI_VER}-${REVISION}${suf}.${ARCH}.rpm"
	pkg="$pkg $pkg1"
	rm -f $pkg1
	# ATTENTION: This could be dangerous for your setup
	opt="rm -rf /usr/lib/mindi ;"
fi
if [ "`echo $c | grep mondo-doc`" != "" ]; then
	cd ${BASE}/svn
	$TOOLHOME/mkspec ${MONDO_VER} mondo-${MONDO_VER}/distributions/rpm/mondo-doc.spec > ${TOPDIR}/SPECS/mondo-doc.spec
	cat mondo-${MONDO_VER}/distributions/$dfam/changelog >> ${TOPDIR}/SPECS/mondo-doc.spec
	chmod 644 ${TOPDIR}/SPECS/mondo-doc.spec

	pkg1="${TOPDIR}/RPMS/${ARCH}/mondo-doc-${MONDO_VER}-${REVISION}${suf}.${ARCH}.rpm"
	pkg="$pkg $pkg1"
	rm -f $pkg1
fi

if [ "`echo $c | grep -v doc | grep mondo`" != "" ]; then
	cd ${BASE}/svn
	$TOOLHOME/mkspec ${MONDO_VER} mondo-${MONDO_VER}/distributions/rpm/mondo.spec > ${TOPDIR}/SPECS/mondo.spec
	cat mondo-${MONDO_VER}/distributions/$dfam/changelog >> ${TOPDIR}/SPECS/mondo.spec
	chmod 644 ${TOPDIR}/SPECS/mondo.spec
	rm -rf mondo-${MONDO_VER}/distributions

	pkg1="${TOPDIR}/RPMS/${ARCH}/mondo-${MONDO_VER}-${REVISION}${suf}.${ARCH}.rpm"
	pkg="$pkg $pkg1"
	rm -f $pkg1
fi

cd ${TOPDIR}/SPECS
status=0

for p in $c; do
	echo "Generating $p RPMS"
	log=/tmp/$p-rpm.log
	rpmbuild -ba $p.spec 2> $log 1> $log
	if [ $? != 0 ]; then 
		cat $log
		status=-1
	fi
done
if [ $status = 0 ]; then
	echo "Installing RPMS as root ($pkg)"
	su - -c "$opt rpm -Uvh --force $pkg"
fi
