#!/bin/bash
#
# Creates common environment for SVN repository
#
# $Id$
#

export SVNBRANCH="branches/`cat ${TOOLHOME}/../mondo/VERSION`"
export MINDI_VER=`cat ${BASE}/svn/${SVNBRANCH}/mindi/VERSION`
export MONDO_VER=`cat ${BASE}/svn/${SVNBRANCH}/mondo/VERSION`

# To be safe for SVN commands
cd $TOOLHOME/..
export REVISION=`svnversion .`
export TAG=`cat ${TOOLHOME}/TAG
