.TH mondoarchive 8 "September 2005" Linux MondoRescue

.SH NAME
mondoarchive \- a backup / disaster\-recovery tool.

.SH SYNOPSIS
.B mondoarchive -O
[
.I options
] : backup your PC
.br
.B mondoarchive -V
[
.I options
] : verify your backup

.SH DESCRIPTION
.PP
.I mondoarchive
backs up a subset of your files, your entire filesystem, or even images of
non-Linux filesystems to CD's, tape, ISO images or an NFS mount. In the event of
catastrophic data loss, you will be able to restore everything, taking a PC from
bare metal to its original state if necessary. 

.pp
With
.BR \-O ,
it backs up your filesystem to CD, tape, ISO images or NFS share. Boot floppies
or a special boot CD will be created to allow you to restore from bare metal if
necessary.

.pp
With
.BR \-V ,
it verifies the backup against the live filesystem. This option may be used in
combination with
.BR \-O
to verify a backup after its creation, or on its own to see how much the live
filesystem has changed since the backup was made.

.pp
Call mondoarchive 
.BR without
.BR flags 
to make it auto-detect as many settings as possible, ask you politely for the
rest, and then backup and verify your OS or a subset thereof.

.pp
To restore data, either run 
.I mondorestore
from the command line or boot from the emergency CD/floppies generated during
the backup process. The latter will come in handy if a gremlin wipes your hard
disk.

.SH BACKUP MEDIA
.TP 13
You must specify one of the following:-

.TP
.BI "-c " speed
Use CD-R drive as backup device and its (write-once) disks as backup media.

.TP
.BI "-w " speed
Use CD-RW drive as backup device and its (write/rewrite) disks as backup media.
Mondo will wipe media before writing to them.

.TP
.BI "-r "
Use DVD drive as backup device and its disks as backup media. Growisofs decides
on the best speed for your drive.

.TP
.BI "-C " speed
Use CD-R drive as a streaming device, almost like a tape streamer. Use
write-once disks as backup media.
.B Experimental.

.TP
.BI "-p " prefix
Use 
.B prefix 
to generate the name of your ISO images.
By default, mondoarchive calls images mondorescue-1.iso, mondorescue-2.iso, ...
Using 
.B -p machine
it will call your images machine-1.iso, machine-2.iso, ...

.TP
.BI "-i "
Use ISO files (CD images) as backup media. This is good for backing up your
system to a spare hard drive. The
.B -n
switch is a wiser choice if you plan to restore from a remote filesystem.

.TP
.BI "-n " mount
Use files residing on NFS partition as backup media.
.I mount
is the remote mount-point, e.g. '192.168.1.3:/home/nfs'
for my file server. Please mount it before backing up/verifying.

.TP
.BI "-t "
Use tape streamer as backup device and its tapes as backup media.

.TP
.BI "-u "
Use a generic streaming device as backup device. Use this if you want to write
your backup to a device that is not directly support by mondoarchive. This will
send the data directly to a raw device.
.B For experienced users only.

.SH MAJOR OPTIONS
.TP 13
.BI "-D "
Make a differential backup: examine the filesystem and find which files have
changed since the last full backup was carried out. Backup only those files.

.TP
.BI "-E " "\*(lqpath ...\*(rq"
Exclude path(s) from backup. The paths should be separated with a whitespace.
Note that mondo automatically excludes removable media (/mnt/floppy,
/mnt/cdrom, etc.). For example, if you are backing up to an NFS mount but you
do not want to include the contents of the mount in a backup, exclude your
local mount-point with this switch. It will also work with partitions, e.g.
/dev/sdd4 if you have a peculiar SCSI zip drive which insists on showing up in
the mountlist. NB: If you exclude /dev/sdd4 then the /dev entry itself will
still be backed up, even though the mountlist entry will be suppressed.

.TP
.BI "-I " "\*(lqpath ...\*(rq"
Include paths(s) in backup. The default backup path is \*(lq/\*(rq but you may
specify alternatives, e.g. -I \*(lq/home /etc\*(rq to override that.

.TP
.BI "-J " "file"
Specify an explicit list of files and directories in a plain text file, one item
(file or directory) per line.

.TP
.BI "-N"
Exclude all mounted network filesystems. This currently means NFS, SMB, Coda
and Netware. In other words, only backup the local hard disk(s).

.TP
.BI "-d " "dev|dir"
Specify the backup device (CD/tape) or directory (NFS/ISO). For CD-R[W] drives,
this is the SCSI node where the drive may be found, e.g. '0,1,0'. For tape
users, this is the tape streamers /dev entry, e.g. '/dev/st0'. For ISO users,
this is the directory where the ISO images are stored. For NFS users, this is
the directory within the NFS mount where the backups are stored. The default
for ISO and NFS is '/root/images/mondo'.

.TP
.BI "-g "
GUI mode. Without this switch, the screen output of mondoarchive is suitable
for processing by an 'expect' wrapper, enabling the user to backup nightly via
a cron job. However, if you want to run this program with an attractive but
non-cron-friendly interface then use '-g'.

.TP
.BI "-k " "path"
Path of user's kernel. If you are a Debian or Gentoo user then specify
.B -k FAILSAFE
as your kernel. Otherwise, you will rarely need this option.

.TP
.BI "-m "
Manual (not self-retracting) CD trays are often found on laptops. If you are
a laptop user, your CD burner has BurnProof technology or you experience 
problems with mondo then please call mondoarchive with this switch. 

.TP
.BI "-o "
Use LILO as boot loader of boot floppy/CD instead of SYSLINUX/ISOLINUX. By
default, SYSLINUX is used for floppies and ISOLINUX for CD's. Use LILO if you
prefer to use that boot loader. NB: This does not affect which boot loader you
use to boot your PC, merely the boot loader used by the CD's/floppies created
by Mondo. Use ELILO instead which is mandatory for IA64 machines.

.TP
.BI "-s " "size"
How much can each of your backup media hold? You may use 'm' and 'g' on the end
of the number, e.g. '700m' for an extra-large CD-R. You no longer need to
specify the size of your cartridges if you are backing up to tape.

.TP
.BI "-x " "'dev ...'"
Specify non-Linux partitions which you want to backup, e.g. NTFS or BeOS.


.SH MINOR OPTIONS
.TP 13
.BI "-[0-9] "
Specify the compression level. Default is 3. No compression is 0.

.TP
.BI "-A " "command"
This command will be called after each CD/NFS/ISO file is written. It is useful
if you want to do something with an ISO after creating it, e.g. write it to a
CD burner using a non-standard command.
.B -A
understands two tokens - _ISO_ and _CD#_ - which will be translated into the
ISO's filename and its index number (1, 2, ...) respectively. So, you could use
.I -A 'foobackup _ISO_; rm -f _ISO_'
to feed each ISO to some magical new backup tool.

.TP
.BI "-B " "command"
This command will be called before each CD/NFS/ISO file is written. See
.B -A
for more information.

.TP
.BI "-F "
Do not offer to write boot+data floppy disk images to 3.5-inch floppy disks.
The images will remain in /root/images/mindi until your next backup run,
however.

.TP
.BI "-H "
When you boot from the tape/CD, your hard drive will be wiped and the archives
will be restored. Your decision to boot from the tape/CD will be taken as
consent. No further permission will be sought.
.B Use with caution.

.TP
.BI "-L "
Use lzo, a fast compression engine, instead of bzip2. You may find lzo on
Mondo's website or via FreshMeat. WARNING! Some versions of LZO are unstable.

.TP
.BI "-R "
EXPERIMENTAL. Do not use in mission-critical environments. Star is an alternative to afio. Mondo now supports POSIX ACLs and extended attributes, so -R is essentially redundant for now.

.TP
.BI "-P " "tarball"
Post-nuke tarball. If you boot into Nuke Mode and everything is restored
successfully then the 
.I post-nuke
script will be sought and executed if found. This is useful for post-restore
customization. It is assumed that the tarball (.tar.gz format) will contain not
just the
.I post-nuke
script (or binary, or whatever it is) but also any files it requires. 

.TP
.BI "-S " "path"
Specify the scratchdir, the directory where ISO images are built before being
archived. If you have plenty of RAM and want to use a ramdisk for scratch
space, specify its path here.

.TP
.BI "-T " "path"
Specify the tempdir, the directory where temporary files (other than ISO images
being assembled) are stored. See
.B -S

.TP
.BI "-W "
Don't make your backup self-booting. This is a really bad idea, IMO. Don't do
this unless you have really great boot disks in your hand and you are an anally
retentive SOB who can't wait 2 minutes for Mindi to run in the background. If
you use -W then you'd better know what the hell you're doing, okay?

.TP
.BI "-b "
Specify the internal block size used by the tape drive. This is usually 32K but
some drives just don't like that. They should but they don't. That's what
happens when tape drive vendors don't talk to kernel driver writers. Try 512 or
16384.

.TP
.BI "-e "
Don't eject the CD or tape when backing up or restoring... unless cdrecord
insists on it. If it does, well, tough. Sorry. :)

.TP
.BI "-f " "device"
Specify the drive on which your Master Boot Record lives. Usually, this is
discovered automatically.

.TP
.BI "-l " "GRUB|LILO|ELILO|RAW"
Specify the boot loader. By default, your Master Boot Record is examined and
the boot loader can usually be discovered. If you specify RAW then the MBR will
be backed up and restored byte-for-byte without any analysis. It is likely that
you will also need to specify the boot device with -f <dev>. ELILO is mandatory
for IA64 machines.

.TP
.BI "-Q "
Give more detailed information about the boot loader.

.TP
.BI "-K " "loglevel"
Specify the loglevel.


.SH DIAGNOSTICS
Mondo generates two additional, and Extremely important files:
.BI /var/log/mindi.log
and
.BI /var/log/mondo-archive.log. 
When seeking technical support, attach these two files to your email. 



.SH FILES
.IR /var/log/mindi.log  
This log contains important information required to analyse mindi problem
reports.

.IR /var/log/mondo-archive.log
This log contains important information required to analyse mondoarchive
problem reports. Mondo support highly recommends sending these files with
support questions.

.SH NOTES
A link to Mondo's HTML-based manual (by Mikael Hultgren, Cafeole, Randy Delphs,
Stan Benoit, and me) may be found at
.I http://www.microwerks.net/~hugo/docs/docs.html
- or in 
.I /usr/share/doc/mondo-x.xx
on your hard drive.
A link to test results can be found at 
.I http://www.nakedsoul.org/~troff


.SH BUGS
It is recommend that your system has more than 64 MB ram. SCSI device order
change with nuke can have unexpected results. It is recommended you use expert
mode with drastic hardware reconfigurations. 

.SH EXAMPLES

.BI ISO:
Backup to a directory; note that /mnt/foo's contents will be backed up except
for its ISO's unless you exclude it, as follows:-
.br
.I "mondoarchive -Oi -d /mnt/foo -E /mnt/foo"

Backup to ISO's non-interactively, e.g. as a job running in /etc/cron.daily:
.br
.I "mkdir -p /bkp/`date +%A`; mondoarchive -Oi -9 -d /bkp/`date +%A` -E /bkp"

.BI DVD:
Backup PC using DVD Media:
.br
.I "mondoarchive -OVr 2 -d /dev/scd0 -gF -s 4200m"

.BI TAPE:
Backup to tape, using lzo compression (WARNING - can be unstable):
.br
.I "mondoarchive -Ot -d /dev/st0 -L"

Verify existing tape backup which was made with lzo compression:-
.br
.I "mondoarchive -Vt -d /dev/st0 -L -g"

Backup to tape, using max compression:
.br
.I "mondoarchive -Ot -9 -d /dev/st0 "

.BI CD-R:
Backup to 700MB CD-R disks using a 16x CD burner:
.br
.I "mondoarchive -Oc 16 -s 700m -g"

Verify existing CD-R or CD-RW backup (works for either):-
.br
.I "mondoarchive -Vc 16"

.BI CD-RW:
Backup to 650MB CD-RW disks using a 4x CD ReWriter:
.br
.I "mondoarchive -Ow 4"

Backup just your /home and /etc directory to 650MB CD-RW disks using a 4x CD
ReWriter:
.br
.I "mondoarchive -Ow 4 -I \*(lq/home /etc\*(rq"

.BI NFS:
Backup to an NFS mount:
.br
.I "mondoarchive -On 192.168.1.2:/home/nfs -d /Monday -E /mnt/nfs"

Verify existing NFS backup:-
.br
.I "mondoarchive -Vn 192.168.1.2:/home/nfs -d /Monday"

.BI RAID:
Backup PC to a Software Raid mount point, iso size 700mb:
.br
.I "mondoarchive -O -s 700m -d /mnt/raid" 


.SH "SEE ALSO"
afio(1), bzip2(1), find(1), mindi(8), mondorestore(8). The mindi manual
might not have been written yet.
.SH AUTHORS
Hugo Rabson (coding)
.I "hugorabson@msn.comt"
.br
Jesse Keating (packaging)
.I "hosting@j2solutions.net"
.br
Stan Benoit (testing)
.I "troff@nakedsoul.org"
.br
Mikael Hultgren (docs)
.I "mikael_hultgren@gmx.net"
.br
See mailing list at http://www.mondorescue.com for technical support.
.
